### ISSUE TITLE
Test Files

### ISSUE THREAD

**Issue by n0tr00t3r** [dosentmatter/nbrplay-vagrant#1]
Hello,
I'm doing some research on arf file(cisco webex) recently, so I need some arf files. I found this github project, could you send me some arf files for testing? Thank you very much first.

**Comment by dosentmatter** [comment]
Hey @n0tr00t3r. Sorry, I've stopped using Cisco Webex, so I don't have any old .arf files, and I can't create any new ones.

Why kind of research are you doing. Do you have a Cisco Webex license? If you do, you can get a .arf file by recording your meeting.
